# Generated by Django 2.1.7 on 2019-04-10 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('desc', models.TextField(max_length=800)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('politics', 'Politics'), ('entertainment', 'Entertainment')], max_length=50)),
                ('url', models.URLField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('url', models.URLField(blank=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
