# Generated by Django 2.1.7 on 2019-04-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20190401_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('desc', models.TextField(max_length=800)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('politics', 'Politics'), ('entertainment', 'Entertainment')], max_length=50)),
                ('url', models.URLField(blank=True)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
