# Generated by Django 2.1.7 on 2019-04-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190405_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('url', models.URLField(blank=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
        ),
    ]
