# Generated by Django 2.1.7 on 2019-04-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jkel',
            field=models.CharField(choices=[('laki-laki', 'Laki-Laki'), ('perempuan', 'Perempuan')], max_length=50),
        ),
    ]
