# Generated by Django 2.1.7 on 2019-04-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190401_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alamat',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='jkel',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nmlgkp',
            new_name='name',
        ),
    ]
